name: Deploy UserScript

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy script to output dir
        run: |
          mkdir -p public
          cp *.user.js public/
          cp DeleteAllPixVerse.user.js public/my-script.meta.js  # Tampermonkey needs .meta.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
